Guard against duplicate authority
There appear to be two LCSH entries with id "sh 85012819" in Voyager. Such cases are probably duplicates, but the priority is not to crash due to duplicate keys.

com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-sh 85012819 ' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.Util.getInstance(Util.java:360)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:971)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2141)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2077)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2062)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1449)
	at edu.cornell.library.integration.indexer.IndexAuthorityRecords.getAuthorityId(IndexAuthorityRecords.java:571)
	at edu.cornell.library.integration.indexer.IndexAuthorityRecords.processAuthorityMarc(IndexAuthorityRecords.java:329)
	at edu.cornell.library.integration.indexer.IndexAuthorityRecords.processFile(IndexAuthorityRecords.java:109)
	at edu.cornell.library.integration.indexer.IndexAuthorityRecords.<init>(IndexAuthorityRecords.java:89)
	at edu.cornell.library.integration.indexer.IndexAuthorityRecords.main(IndexAuthorityRecords.java:64)