Return empty list of OCLC ids if the Solr field other_id_display is empty
To prevent a NPE:

java.lang.Exception: Could not create solr document for
http://da-rdf.library.cornell.edu/individual/b9255624indexing 114 out of
1000. bib URI: http://da-rdf.library.cornell.edu/individual/b8848561
at
edu.cornell.library.integration.hadoop.map.BibFileIndexingMapper.indexToSolr(BibFileIndexingMapper.java:278)
at
edu.cornell.library.integration.hadoop.map.BibFileIndexingMapper.map(BibFileIndexingMapper.java:175)
at
edu.cornell.library.integration.indexer.IndexDirectory.indexDocuments(IndexDirectory.java:155)
at
edu.cornell.library.integration.indexer.updates.IncrementalBibFileToSolr.main(IncrementalBibFileToSolr.java:74)
Caused by: java.lang.NullPointerException
at
edu.cornell.library.integration.indexer.documentPostProcess.UpdateSolrInventoryDB.extractOclcIdsFromSolrField(UpdateSolrInventoryDB.java:126)
at
edu.cornell.library.integration.indexer.documentPostProcess.UpdateSolrInventoryDB.updateWorkInfo(UpdateSolrInventoryDB.java:208)
at
edu.cornell.library.integration.indexer.documentPostProcess.UpdateSolrInventoryDB.p(UpdateSolrInventoryDB.java:81)
at
edu.cornell.library.integration.indexer.RecordToDocumentBase.buildDoc(RecordToDocumentBase.java:118)
at
edu.cornell.library.integration.hadoop.map.BibFileIndexingMapper.indexToSolr(BibFileIndexingMapper.java:272)
... 3 more