Avoid NPE for bib with no main title
Bibs without titles shouldn't happen, but do on occasion. This is
causing the UpdateSolrInventoryDB logic to cause the generation of the
Solr document to fail for that bib:

TitleRport: http://da-rdf.library.cornell.edu/individual/b9667629 has no
title.
java.lang.Exception: Could not create solr document for
http://da-rdf.library.cornell.edu/individual/b9667629
at
edu.cornell.library.integration.hadoop.map.BibFileIndexingMapper.indexToSolr(BibFileIndexingMapper.java:277)
at
edu.cornell.library.integration.hadoop.map.BibFileIndexingMapper.map(BibFileIndexingMapper.java:175)
at
edu.cornell.library.integration.indexer.IndexDirectory.indexDocuments(IndexDirectory.java:155)
at
edu.cornell.library.integration.indexer.updates.IncrementalBibFileToSolr.<init>(IncrementalBibFileToSolr.java:78)
at
edu.cornell.library.integration.indexer.updates.IterativeUpdateFromVoyager.main(IterativeUpdateFromVoyager.java:48)
Caused by: java.lang.NullPointerException
at
edu.cornell.library.integration.utilities.IndexingUtilities.pullReferenceFields(IndexingUtilities.java:278)
at
edu.cornell.library.integration.indexer.documentPostProcess.UpdateSolrInventoryDB.populateBibField(UpdateSolrInventoryDB.java:427)
at
edu.cornell.library.integration.indexer.documentPostProcess.UpdateSolrInventoryDB.p(UpdateSolrInventoryDB.java:67)
at
edu.cornell.library.integration.indexer.RecordToDocumentBase.buildDoc(RecordToDocumentBase.java:118)
at
edu.cornell.library.integration.hadoop.map.BibFileIndexingMapper.indexToSolr(BibFileIndexingMapper.java:271)
... 4 more

The job continues to the end of the batch, but then
IncrementalBibFileToSolr triggers a job failure due to the error:

Exception in thread "main" java.lang.Exception: There were errors during
indexing.
at
edu.cornell.library.integration.indexer.updates.IncrementalBibFileToSolr.checkForErrors(IncrementalBibFileToSolr.java:113)
at
edu.cornell.library.integration.indexer.updates.IncrementalBibFileToSolr.<init>(IncrementalBibFileToSolr.java:85)
at
edu.cornell.library.integration.indexer.updates.IterativeUpdateFromVoyager.main(IterativeUpdateFromVoyager.java:48)
http://da-rdf.library.cornell.edu/individual/b9667629 URI Error Could
not create solr document for
http://da-rdf.library.cornell.edu/individual/b9667629